<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/assignUserToTeam.proto

namespace grpc\AssignUserToTeam;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AssignUserToTeam.AssignUserToTeamRequest</code>
 */
class AssignUserToTeamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     */
    protected $action_by_user_id = 0;
    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     */
    protected $team_id = 0;
    /**
     * Generated from protobuf field <code>repeated .AssignUserToTeam.fK fk = 3;</code>
     */
    private $fk;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     *     @type int|string $team_id
     *     @type \grpc\AssignUserToTeam\fK[]|\Google\Protobuf\Internal\RepeatedField $fk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\AssignUserToTeam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AssignUserToTeam.fK fk = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>repeated .AssignUserToTeam.fK fk = 3;</code>
     * @param \grpc\AssignUserToTeam\fK[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFk($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\AssignUserToTeam\fK::class);
        $this->fk = $arr;

        return $this;
    }

}

