<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/assignUserToTeam.proto

namespace grpc\AssignUserToTeam;

use Spiral\RoadRunner\GRPC;

interface AssignUserToTeamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "AssignUserToTeam.AssignUserToTeamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AssignUserToTeamRequest $in
    * @return AssignUserToTeamResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AssignUser(GRPC\ContextInterface $ctx, AssignUserToTeamRequest $in): AssignUserToTeamResponse;
}
