<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/assignUserToTeam.proto

namespace grpc\AssignUserToTeam;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AssignUserToTeam.fK</code>
 */
class fK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     */
    protected $fk = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\AssignUserToTeam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @return int|string
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFk($var)
    {
        GPBUtil::checkInt64($var);
        $this->fk = $var;

        return $this;
    }

}

