<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/DeleteTeam.proto

namespace grpc\DeleteTeam;

use Spiral\RoadRunner\GRPC;

interface DeleteTeamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "DeleteTeam.DeleteTeamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeleteTeamRequest $in
    * @return DeleteTeamResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteTeam(GRPC\ContextInterface $ctx, DeleteTeamRequest $in): DeleteTeamResponse;
}
