<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getArchives.proto

namespace grpc\GetArchives;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetArchives.GetArchivesResponse</code>
 */
class GetArchivesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GetArchives.GetArchives archives = 1;</code>
     */
    private $archives;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\GetArchives\GetArchives[]|\Google\Protobuf\Internal\RepeatedField $archives
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetArchives::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GetArchives.GetArchives archives = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArchives()
    {
        return $this->archives;
    }

    /**
     * Generated from protobuf field <code>repeated .GetArchives.GetArchives archives = 1;</code>
     * @param \grpc\GetArchives\GetArchives[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArchives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\GetArchives\GetArchives::class);
        $this->archives = $arr;

        return $this;
    }

}

