<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/getArchives.proto

namespace grpc\GetArchives;

use Spiral\RoadRunner\GRPC;

interface GetArchivesServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "GetArchives.GetArchivesService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetArchivesRequest $in
    * @return GetArchivesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetArchives(GRPC\ContextInterface $ctx, GetArchivesRequest $in): GetArchivesResponse;
}
