<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/AddArchive.proto

namespace grpc\AddArchive;

use Spiral\RoadRunner\GRPC;

interface AddArchiveServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "AddArchive.AddArchiveService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AddArchiveRequest $in
    * @return AddArchiveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AddArchive(GRPC\ContextInterface $ctx, AddArchiveRequest $in): AddArchiveResponse;
}
