services:
  mysql:
    container_name: ums-mysql-1
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3007:3306"
    networks:
      - network

  redis:
    image: redis:alpine
    restart: unless-stopped
    # ports:
    #   - "6380:6379"
    networks:
      - network
      - shared_net

  app:
    container_name: ums-app-1
    build:
      context: .
    image: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/html/sunset/user_management_service
    volumes:
      - .:/var/www/html/sunset/user_management_service
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
    ports:
      - "8001:9001"
    networks:
      - network
      - grpc_network

volumes:
  dbdata:

networks:
  network:
  shared_net:
  grpc_network:
    name: grpc_network
    driver: bridge
    external: true
	
