<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/getUsers.proto

namespace grpc\getUsers;

use Spiral\RoadRunner\GRPC;

interface GetUsersServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "getUsers.GetUsersService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetUsersRequest $in
    * @return GetUsersResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetUsers(GRPC\ContextInterface $ctx, GetUsersRequest $in): GetUsersResponse;
}
