<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/getUserDetails.proto

namespace grpc\GetUserDetails;

use Spiral\RoadRunner\GRPC;

interface GetUserDetailsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "getUserDetails.GetUserDetailsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetUserDetailsRequest $in
    * @return GetUserDetailsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetUserDetails(GRPC\ContextInterface $ctx, GetUserDetailsRequest $in): GetUserDetailsResponse;
}
