<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/userClockOut.proto

namespace grpc\userClockOut;

use Spiral\RoadRunner\GRPC;

interface UserClockOutServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "userClockOut.UserClockOutService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserClockOutRequest $in
    * @return UserClockOutResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SetUserClockOut(GRPC\ContextInterface $ctx, UserClockOutRequest $in): UserClockOutResponse;
}
