<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/userClockOut.proto

namespace grpc\userClockOut;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>userClockOut.UserClockOutRequest</code>
 */
class UserClockOutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     */
    protected $fk = 0;
    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     */
    protected $timezone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fk
     *     @type string $timezone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\UserClockOut::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @return int|string
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFk($var)
    {
        GPBUtil::checkInt64($var);
        $this->fk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

}

