<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/overview.proto

namespace grpc\Overview;

use Spiral\RoadRunner\GRPC;

interface OverviewServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "Overview.OverviewService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param OverviewRequest $in
    * @return OverviewResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Overview(GRPC\ContextInterface $ctx, OverviewRequest $in): OverviewResponse;
}
