<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/overview.proto

namespace grpc\Overview;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Overview.UserDetail</code>
 */
class UserDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string date = 1;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>int64 totalUser = 2;</code>
     */
    protected $totalUser = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $date
     *     @type int|string $totalUser
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\Overview::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string date = 1;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalUser = 2;</code>
     * @return int|string
     */
    public function getTotalUser()
    {
        return $this->totalUser;
    }

    /**
     * Generated from protobuf field <code>int64 totalUser = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalUser = $var;

        return $this;
    }

}

