<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/overview.proto

namespace grpc\Overview;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Overview.UserDetailUserRole</code>
 */
class UserDetailUserRole extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_role_id = 2;</code>
     */
    protected $user_role_id = 0;
    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>string user_role = 4;</code>
     */
    protected $user_role = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_role_id
     *     @type int|string $count
     *     @type string $user_role
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\Overview::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_role_id = 2;</code>
     * @return int|string
     */
    public function getUserRoleId()
    {
        return $this->user_role_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_role_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserRoleId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_role_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_role = 4;</code>
     * @return string
     */
    public function getUserRole()
    {
        return $this->user_role;
    }

    /**
     * Generated from protobuf field <code>string user_role = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_role = $var;

        return $this;
    }

}

