<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/CreateDepartment.proto

namespace grpc\CreateDepartment;

use Spiral\RoadRunner\GRPC;

interface CreateDepartmentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "CreateDepartment.CreateDepartmentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CreateDepartmentRequest $in
    * @return CreateDepartmentResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateDepartment(GRPC\ContextInterface $ctx, CreateDepartmentRequest $in): CreateDepartmentResponse;
}
