<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/userClockIn.proto

namespace grpc\userClockIn;

use Spiral\RoadRunner\GRPC;

interface UserClockInServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "userClockIn.UserClockInService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserClockInRequest $in
    * @return UserClockOutResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UserClockInService(GRPC\ContextInterface $ctx, UserClockInRequest $in): UserClockOutResponse;
}
