<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/getLogs.proto

namespace grpc\GetLogs;

use Spiral\RoadRunner\GRPC;

interface GetLogsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "GetLogs.GetLogsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetLogsRequest $in
    * @return GetLogsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetLogs(GRPC\ContextInterface $ctx, GetLogsRequest $in): GetLogsResponse;
}
