<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getLogs.proto

namespace grpc\GetLogs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetLogs.GetLogsResponse</code>
 */
class GetLogsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GetLogs.Logs logs = 1;</code>
     */
    private $logs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\GetLogs\Logs[]|\Google\Protobuf\Internal\RepeatedField $logs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetLogs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GetLogs.Logs logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * Generated from protobuf field <code>repeated .GetLogs.Logs logs = 1;</code>
     * @param \grpc\GetLogs\Logs[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\GetLogs\Logs::class);
        $this->logs = $arr;

        return $this;
    }

}

