<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getLogs.proto

namespace grpc\GetLogs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetLogs.GetLogsRequest</code>
 */
class GetLogsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     */
    protected $fk = 0;
    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     */
    protected $timezone = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>int64 current_page = 4;</code>
     */
    protected $current_page = 0;
    /**
     * Generated from protobuf field <code>int64 per_page = 5;</code>
     */
    protected $per_page = 0;
    /**
     * Generated from protobuf field <code>string search = 6;</code>
     */
    protected $search = '';
    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     */
    protected $sort = '';
    /**
     * Generated from protobuf field <code>string sort_column = 8;</code>
     */
    protected $sort_column = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fk
     *     @type string $timezone
     *     @type string $description
     *     @type int|string $current_page
     *     @type int|string $per_page
     *     @type string $search
     *     @type string $sort
     *     @type string $sort_column
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetLogs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @return int|string
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFk($var)
    {
        GPBUtil::checkInt64($var);
        $this->fk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 current_page = 4;</code>
     * @return int|string
     */
    public function getCurrentPage()
    {
        return $this->current_page;
    }

    /**
     * Generated from protobuf field <code>int64 current_page = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->current_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 per_page = 5;</code>
     * @return int|string
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>int64 per_page = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string search = 6;</code>
     * @return string
     */
    public function getSearch()
    {
        return $this->search;
    }

    /**
     * Generated from protobuf field <code>string search = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     * @return string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort_column = 8;</code>
     * @return string
     */
    public function getSortColumn()
    {
        return $this->sort_column;
    }

    /**
     * Generated from protobuf field <code>string sort_column = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSortColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort_column = $var;

        return $this;
    }

}

