<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/RemoveUserTeam.proto

namespace grpc\RemoveUserTeam;

use Spiral\RoadRunner\GRPC;

interface RemoveUserTeamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "RemoveUserTeam.RemoveUserTeamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RemoveUserTeamRequest $in
    * @return RemoveUserTeamResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RemoveUserTeam(GRPC\ContextInterface $ctx, RemoveUserTeamRequest $in): RemoveUserTeamResponse;
}
