<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/RemoveUserTeam.proto

namespace grpc\RemoveUserTeam;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RemoveUserTeam.RemoveUserTeamRequest</code>
 */
class RemoveUserTeamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     */
    protected $action_by_user_id = 0;
    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     */
    protected $team_id = 0;
    /**
     * Generated from protobuf field <code>string timezone = 3;</code>
     */
    protected $timezone = '';
    /**
     * Generated from protobuf field <code>int64 fk = 4;</code>
     */
    protected $fk = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     *     @type int|string $team_id
     *     @type string $timezone
     *     @type int|string $fk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\RemoveUserTeam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 3;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 4;</code>
     * @return int|string
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFk($var)
    {
        GPBUtil::checkInt64($var);
        $this->fk = $var;

        return $this;
    }

}

