<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/userClockOut.proto

namespace GPBMetadata\Ums;

class UserClockOut
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a16756d732f75736572436c6f636b4f75742e70726f746f120c75736572436c6f636b4f757422330a1355736572436c6f636b4f757452657175657374120a0a02666b18012001280312100a0874696d657a6f6e6518022001280922260a1455736572436c6f636b4f7574526573706f6e7365120e0a06726573756c74180120012808326f0a1355736572436c6f636b4f75745365727669636512580a0f53657455736572436c6f636b4f757412212e75736572436c6f636b4f75742e55736572436c6f636b4f7574526571756573741a222e75736572436c6f636b4f75742e55736572436c6f636b4f7574526573706f6e73654214ca0211677270635c75736572436c6f636b4f7574620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

