<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/userClockIn.proto

namespace GPBMetadata\Ums;

class UserClockIn
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b020a15756d732f75736572436c6f636b496e2e70726f746f120b75736572436c6f636b496e22320a1255736572436c6f636b496e52657175657374120a0a02666b18012001280312100a0874696d657a6f6e6518022001280922250a1355736572436c6f636b496e526573706f6e7365120e0a06726573756c74180120012808326d0a1255736572436c6f636b496e5365727669636512570a1255736572436c6f636b496e53657276696365121f2e75736572436c6f636b496e2e55736572436c6f636b496e526571756573741a202e75736572436c6f636b496e2e55736572436c6f636b496e526573706f6e73654213ca0210677270635c75736572436c6f636b496e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

