<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/SuggestedMemberDepartment.proto

namespace grpc\SuggestedMemberDepartment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SuggestedMemberDepartment.SuggestedMemberDepartmentResponse</code>
 */
class SuggestedMemberDepartmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .SuggestedMemberDepartment.departmentMember department_lists = 1;</code>
     */
    private $department_lists;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\SuggestedMemberDepartment\departmentMember[]|\Google\Protobuf\Internal\RepeatedField $department_lists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\SuggestedMemberDepartment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .SuggestedMemberDepartment.departmentMember department_lists = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDepartmentLists()
    {
        return $this->department_lists;
    }

    /**
     * Generated from protobuf field <code>repeated .SuggestedMemberDepartment.departmentMember department_lists = 1;</code>
     * @param \grpc\SuggestedMemberDepartment\departmentMember[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDepartmentLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\SuggestedMemberDepartment\departmentMember::class);
        $this->department_lists = $arr;

        return $this;
    }

}

