<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/SuggestedMemberDepartment.proto

namespace grpc\SuggestedMemberDepartment;

use Spiral\RoadRunner\GRPC;

interface SuggestedMemberDepartmentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "SuggestedMemberDepartment.SuggestedMemberDepartmentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SuggestedMemberDepartmentRequest $in
    * @return SuggestedMemberDepartmentResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SuggestedMemberDepartment(GRPC\ContextInterface $ctx, SuggestedMemberDepartmentRequest $in): SuggestedMemberDepartmentResponse;
}
