<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/teamUsersLists.proto

namespace grpc\TeamUsersLists;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TeamUsersLists.teamUsersLists</code>
 */
class teamUsersLists extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     */
    protected $first_name = '';
    /**
     * Generated from protobuf field <code>string middle_name = 3;</code>
     */
    protected $middle_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     */
    protected $last_name = '';
    /**
     * Generated from protobuf field <code>string position = 5;</code>
     */
    protected $position = '';
    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     */
    protected $profile_image_url = '';
    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     */
    protected $profile_image_name = '';
    /**
     * Generated from protobuf field <code>string created_at = 8;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 9;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $first_name
     *     @type string $middle_name
     *     @type string $last_name
     *     @type string $position
     *     @type string $profile_image_url
     *     @type string $profile_image_name
     *     @type string $created_at
     *     @type string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\TeamUsersLists::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 3;</code>
     * @return string
     */
    public function getMiddleName()
    {
        return $this->middle_name;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMiddleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->middle_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string position = 5;</code>
     * @return string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>string position = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     * @return string
     */
    public function getProfileImageUrl()
    {
        return $this->profile_image_url;
    }

    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     * @return string
     */
    public function getProfileImageName()
    {
        return $this->profile_image_name;
    }

    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 8;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 9;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

