<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/teamUsersLists.proto

namespace grpc\TeamUsersLists;

use Spiral\RoadRunner\GRPC;

interface TeamListsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "TeamUsersLists.TeamListsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TeamUsersListsRequest $in
    * @return TeamUsersListsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function TeamUsersLists(GRPC\ContextInterface $ctx, TeamUsersListsRequest $in): TeamUsersListsResponse;
}
