<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/teamUsersLists.proto

namespace grpc\TeamUsersLists;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TeamUsersLists.TeamUsersListsRequest</code>
 */
class TeamUsersListsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     */
    protected $action_by_user_id = 0;
    /**
     * Generated from protobuf field <code>string time_zone = 3;</code>
     */
    protected $time_zone = '';
    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     */
    protected $team_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     *     @type string $time_zone
     *     @type int|string $team_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\TeamUsersLists::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 3;</code>
     * @return string
     */
    public function getTimeZone()
    {
        return $this->time_zone;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_zone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

}

