<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/teamUsersLists.proto

namespace grpc\TeamUsersLists;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TeamUsersLists.TeamUsersListsResponse</code>
 */
class TeamUsersListsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     */
    protected $team_name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>repeated .TeamUsersLists.teamUsersLists team_lists = 6;</code>
     */
    private $team_lists;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $team_name
     *     @type string $description
     *     @type string $created_at
     *     @type string $updated_at
     *     @type \grpc\TeamUsersLists\teamUsersLists[]|\Google\Protobuf\Internal\RepeatedField $team_lists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\TeamUsersLists::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     * @return string
     */
    public function getTeamName()
    {
        return $this->team_name;
    }

    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTeamName($var)
    {
        GPBUtil::checkString($var, True);
        $this->team_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .TeamUsersLists.teamUsersLists team_lists = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTeamLists()
    {
        return $this->team_lists;
    }

    /**
     * Generated from protobuf field <code>repeated .TeamUsersLists.teamUsersLists team_lists = 6;</code>
     * @param \grpc\TeamUsersLists\teamUsersLists[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTeamLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\TeamUsersLists\teamUsersLists::class);
        $this->team_lists = $arr;

        return $this;
    }

}

