<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/EditDepartment.proto

namespace grpc\EditDepartment;

use Spiral\RoadRunner\GRPC;

interface EditDepartmentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "EditDepartment.EditDepartmentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EditDepartmentRequest $in
    * @return EditDepartmentResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function EditDepartment(GRPC\ContextInterface $ctx, EditDepartmentRequest $in): EditDepartmentResponse;
}
