<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/DeleteDepartment.proto

namespace grpc\DeleteDepartment;

use Spiral\RoadRunner\GRPC;

interface DeleteDepartmentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "DeleteDepartment.DeleteDepartmentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeleteDepartmentRequest $in
    * @return DeleteDepartmentResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteDepartment(GRPC\ContextInterface $ctx, DeleteDepartmentRequest $in): DeleteDepartmentResponse;
}
