<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/userRegistrationFormData.proto

namespace grpc\userRegistrationFormData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>userRegistrationFormData.UserRegistrationFormDataRequest</code>
 */
class UserRegistrationFormDataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 12;</code>
     */
    protected $action_by_user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\UserRegistrationFormData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 12;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

}

