<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/userRegistrationFormData.proto

namespace grpc\userRegistrationFormData;

use Spiral\RoadRunner\GRPC;

interface UserRegistrationFormDataServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "userRegistrationFormData.UserRegistrationFormDataService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserRegistrationFormDataRequest $in
    * @return UserRegistrationFormDataResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UserRegistrationFormData(GRPC\ContextInterface $ctx, UserRegistrationFormDataRequest $in): UserRegistrationFormDataResponse;
}
