<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/createTeam.proto

namespace grpc\CreateTeam;

use Spiral\RoadRunner\GRPC;

interface CreateTeamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "CreateTeam.CreateTeamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CreateTeamRequest $in
    * @return CreateTeamResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateTeam(GRPC\ContextInterface $ctx, CreateTeamRequest $in): CreateTeamResponse;
}
