<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/createTeam.proto

namespace grpc\CreateTeam;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CreateTeam.CreateTeamRequest</code>
 */
class CreateTeamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     */
    protected $action_by_user_id = 0;
    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     */
    protected $team_name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string time_zone = 4;</code>
     */
    protected $time_zone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     *     @type string $team_name
     *     @type string $description
     *     @type string $time_zone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\CreateTeam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     * @return string
     */
    public function getTeamName()
    {
        return $this->team_name;
    }

    /**
     * Generated from protobuf field <code>string team_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTeamName($var)
    {
        GPBUtil::checkString($var, True);
        $this->team_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 4;</code>
     * @return string
     */
    public function getTimeZone()
    {
        return $this->time_zone;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_zone = $var;

        return $this;
    }

}

