<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/EditUserDetail.proto

namespace grpc\EditUserDetails;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EditUserDetails.EditUserDetailsRequest</code>
 */
class EditUserDetailsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string first_name = 1;</code>
     */
    protected $first_name = '';
    /**
     * Generated from protobuf field <code>string middle_name = 2;</code>
     */
    protected $middle_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     */
    protected $last_name = '';
    /**
     * Generated from protobuf field <code>string email = 4;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string address = 6;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string department = 7;</code>
     */
    protected $department = '';
    /**
     * Generated from protobuf field <code>string date_of_birth = 8;</code>
     */
    protected $date_of_birth = '';
    /**
     * Generated from protobuf field <code>string gender = 9;</code>
     */
    protected $gender = '';
    /**
     * Generated from protobuf field <code>string position = 10;</code>
     */
    protected $position = '';
    /**
     * Generated from protobuf field <code>string profile_image = 11;</code>
     */
    protected $profile_image = '';
    /**
     * Generated from protobuf field <code>string action_by_user_id = 12;</code>
     */
    protected $action_by_user_id = '';
    /**
     * Generated from protobuf field <code>string profile_image_u_r_l = 13;</code>
     */
    protected $profile_image_u_r_l = '';
    /**
     * Generated from protobuf field <code>string profile_image_Name = 14;</code>
     */
    protected $profile_image_Name = '';
    /**
     * Generated from protobuf field <code>int64 fk = 15;</code>
     */
    protected $fk = 0;
    /**
     * Generated from protobuf field <code>string timezone = 16;</code>
     */
    protected $timezone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $first_name
     *     @type string $middle_name
     *     @type string $last_name
     *     @type string $email
     *     @type string $phone
     *     @type string $address
     *     @type string $department
     *     @type string $date_of_birth
     *     @type string $gender
     *     @type string $position
     *     @type string $profile_image
     *     @type string $action_by_user_id
     *     @type string $profile_image_u_r_l
     *     @type string $profile_image_Name
     *     @type int|string $fk
     *     @type string $timezone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\EditUserDetail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 2;</code>
     * @return string
     */
    public function getMiddleName()
    {
        return $this->middle_name;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMiddleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->middle_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string department = 7;</code>
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * Generated from protobuf field <code>string department = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->department = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_of_birth = 8;</code>
     * @return string
     */
    public function getDateOfBirth()
    {
        return $this->date_of_birth;
    }

    /**
     * Generated from protobuf field <code>string date_of_birth = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDateOfBirth($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_of_birth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gender = 9;</code>
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>string gender = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string position = 10;</code>
     * @return string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>string position = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image = 11;</code>
     * @return string
     */
    public function getProfileImage()
    {
        return $this->profile_image;
    }

    /**
     * Generated from protobuf field <code>string profile_image = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action_by_user_id = 12;</code>
     * @return string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>string action_by_user_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_u_r_l = 13;</code>
     * @return string
     */
    public function getProfileImageURL()
    {
        return $this->profile_image_u_r_l;
    }

    /**
     * Generated from protobuf field <code>string profile_image_u_r_l = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageURL($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_u_r_l = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_Name = 14;</code>
     * @return string
     */
    public function getProfileImageName()
    {
        return $this->profile_image_Name;
    }

    /**
     * Generated from protobuf field <code>string profile_image_Name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 15;</code>
     * @return int|string
     */
    public function getFk()
    {
        return $this->fk;
    }

    /**
     * Generated from protobuf field <code>int64 fk = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFk($var)
    {
        GPBUtil::checkInt64($var);
        $this->fk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 16;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

}

