<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/EditUserDetail.proto

namespace grpc\EditUserDetails;

use Spiral\RoadRunner\GRPC;

interface EditUserDetailsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "EditUserDetails.EditUserDetailsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EditUserDetailsRequest $in
    * @return EditUserDetailsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function EditUserDetails(GRPC\ContextInterface $ctx, EditUserDetailsRequest $in): EditUserDetailsResponse;
}
