<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/teamLists.proto

namespace grpc\TeamLists;

use Spiral\RoadRunner\GRPC;

interface TeamListsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "TeamLists.TeamListsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TeamListsRequest $in
    * @return TeamListsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function TeamLists(GRPC\ContextInterface $ctx, TeamListsRequest $in): TeamListsResponse;
}
