<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/register.proto

namespace grpc\Register;

use Spiral\RoadRunner\GRPC;

interface RegisterServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "register.RegisterService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RegisterUserDetailsRequest $in
    * @return RegisterUserDetailsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RegisterUserDetails(GRPC\ContextInterface $ctx, RegisterUserDetailsRequest $in): RegisterUserDetailsResponse;
}
