<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/assignUserShift.proto

namespace grpc\AssignUserShift;

use Spiral\RoadRunner\GRPC;

interface AssignUserShiftServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "AssignUserShift.AssignUserShiftService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AssignUserShiftRequest $in
    * @return AssignUserShiftResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AssignUserShift(GRPC\ContextInterface $ctx, AssignUserShiftRequest $in): AssignUserShiftResponse;
}
