<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/assignUserShift.proto

namespace grpc\AssignUserShift;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AssignUserShift.AssignUserShiftRequest</code>
 */
class AssignUserShiftRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     */
    protected $action_by_user_id = 0;
    /**
     * Generated from protobuf field <code>string shift_id = 2;</code>
     */
    protected $shift_id = '';
    /**
     * Generated from protobuf field <code>repeated string user_ids = 3;</code>
     */
    private $user_ids;
    /**
     * Generated from protobuf field <code>string timezone = 4;</code>
     */
    protected $timezone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $action_by_user_id
     *     @type string $shift_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $user_ids
     *     @type string $timezone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\AssignUserShift::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @return int|string
     */
    public function getActionByUserId()
    {
        return $this->action_by_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 action_by_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionByUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->action_by_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shift_id = 2;</code>
     * @return string
     */
    public function getShiftId()
    {
        return $this->shift_id;
    }

    /**
     * Generated from protobuf field <code>string shift_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShiftId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shift_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string user_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIds()
    {
        return $this->user_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string user_ids = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 4;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

}

