<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getAttendance.proto

namespace grpc\getAttendance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>getAttendance.Attendance</code>
 */
class Attendance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string time_in = 1;</code>
     */
    protected $time_in = '';
    /**
     * Generated from protobuf field <code>string time_out = 2;</code>
     */
    protected $time_out = '';
    /**
     * Generated from protobuf field <code>string time_in_status = 3;</code>
     */
    protected $time_in_status = '';
    /**
     * Generated from protobuf field <code>string time_out_status = 4;</code>
     */
    protected $time_out_status = '';
    /**
     * Generated from protobuf field <code>string created_at = 5;</code>
     */
    protected $created_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $time_in
     *     @type string $time_out
     *     @type string $time_in_status
     *     @type string $time_out_status
     *     @type string $created_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetAttendance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string time_in = 1;</code>
     * @return string
     */
    public function getTimeIn()
    {
        return $this->time_in;
    }

    /**
     * Generated from protobuf field <code>string time_in = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeIn($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_out = 2;</code>
     * @return string
     */
    public function getTimeOut()
    {
        return $this->time_out;
    }

    /**
     * Generated from protobuf field <code>string time_out = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeOut($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_out = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_in_status = 3;</code>
     * @return string
     */
    public function getTimeInStatus()
    {
        return $this->time_in_status;
    }

    /**
     * Generated from protobuf field <code>string time_in_status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeInStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_in_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_out_status = 4;</code>
     * @return string
     */
    public function getTimeOutStatus()
    {
        return $this->time_out_status;
    }

    /**
     * Generated from protobuf field <code>string time_out_status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeOutStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_out_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 5;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

}

