<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/getAttendance.proto

namespace grpc\getAttendance;

use Spiral\RoadRunner\GRPC;

interface GetAttendanceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "getAttendance.GetAttendance";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetAttendanceRequest $in
    * @return GetAttendanceResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetAttendance(GRPC\ContextInterface $ctx, GetAttendanceRequest $in): GetAttendanceResponse;
}
