<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getAttendance.proto

namespace grpc\getAttendance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>getAttendance.GetAttendanceResponse</code>
 */
class GetAttendanceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .getAttendance.Attendance attendance = 1;</code>
     */
    private $attendance;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\getAttendance\Attendance[]|\Google\Protobuf\Internal\RepeatedField $attendance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetAttendance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .getAttendance.Attendance attendance = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttendance()
    {
        return $this->attendance;
    }

    /**
     * Generated from protobuf field <code>repeated .getAttendance.Attendance attendance = 1;</code>
     * @param \grpc\getAttendance\Attendance[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttendance($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\getAttendance\Attendance::class);
        $this->attendance = $arr;

        return $this;
    }

}

