<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/RemoveArchive.proto

namespace grpc\RemoveArchive;

use Spiral\RoadRunner\GRPC;

interface RemoveArchiveServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "RemoveArchive.RemoveArchiveService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RemoveArchiveRequest $in
    * @return RemoveArchiveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RemoveArchive(GRPC\ContextInterface $ctx, RemoveArchiveRequest $in): RemoveArchiveResponse;
}
