<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/GetDepartmentMember.proto

namespace grpc\GetDepartmentMember;

use Spiral\RoadRunner\GRPC;

interface GetDepartmentMemberServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "GetDepartmentMember.GetDepartmentMemberService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetDepartmentMemberRequest $in
    * @return GetDepartmentMemberResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetDepartmentMember(GRPC\ContextInterface $ctx, GetDepartmentMemberRequest $in): GetDepartmentMemberResponse;
}
