<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/GetDepartmentMember.proto

namespace grpc\GetDepartmentMember;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetDepartmentMember.GetDepartmentMemberResponse</code>
 */
class GetDepartmentMemberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string department_name = 2;</code>
     */
    protected $department_name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>repeated .GetDepartmentMember.DepartmentMember department_lists = 6;</code>
     */
    private $department_lists;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $department_name
     *     @type string $description
     *     @type string $created_at
     *     @type string $updated_at
     *     @type \grpc\GetDepartmentMember\DepartmentMember[]|\Google\Protobuf\Internal\RepeatedField $department_lists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetDepartmentMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string department_name = 2;</code>
     * @return string
     */
    public function getDepartmentName()
    {
        return $this->department_name;
    }

    /**
     * Generated from protobuf field <code>string department_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartmentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->department_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .GetDepartmentMember.DepartmentMember department_lists = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDepartmentLists()
    {
        return $this->department_lists;
    }

    /**
     * Generated from protobuf field <code>repeated .GetDepartmentMember.DepartmentMember department_lists = 6;</code>
     * @param \grpc\GetDepartmentMember\DepartmentMember[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDepartmentLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\GetDepartmentMember\DepartmentMember::class);
        $this->department_lists = $arr;

        return $this;
    }

}

