<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/GetDepartmentDetail.proto

namespace grpc\GetDepartmentDetail;

use Spiral\RoadRunner\GRPC;

interface GetDepartmentDetailServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "GetDepartmentDetail.GetDepartmentDetailService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetDepartmentDetailRequest $in
    * @return GetDepartmentDetailResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetDepartmentDetail(GRPC\ContextInterface $ctx, GetDepartmentDetailRequest $in): GetDepartmentDetailResponse;
}
