<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/EditTeam.proto

namespace grpc\EditTeam;

use Spiral\RoadRunner\GRPC;

interface EditTeamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "EditTeam.EditTeamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EditTeamRequest $in
    * @return EditTeamResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function EditTeam(GRPC\ContextInterface $ctx, EditTeamRequest $in): EditTeamResponse;
}
