<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/createShift.proto

namespace grpc\CreateShift;

use Spiral\RoadRunner\GRPC;

interface CreateShiftServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "CreateShift.CreateShiftService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CreateShiftRequest $in
    * @return CreateShiftResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateShift(GRPC\ContextInterface $ctx, CreateShiftRequest $in): CreateShiftResponse;
}
