<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/createShift.proto

namespace grpc\CreateShift;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CreateShift.CreateShiftRequest</code>
 */
class CreateShiftRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string shift_name = 1;</code>
     */
    protected $shift_name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $shift_name
     *     @type string $description
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\CreateShift::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string shift_name = 1;</code>
     * @return string
     */
    public function getShiftName()
    {
        return $this->shift_name;
    }

    /**
     * Generated from protobuf field <code>string shift_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShiftName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shift_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

