<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/GetDepartment.proto

namespace grpc\GetDepartment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetDepartment.GetDepartmentResponse</code>
 */
class GetDepartmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GetDepartment.Departments departments = 1;</code>
     */
    private $departments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\GetDepartment\Departments[]|\Google\Protobuf\Internal\RepeatedField $departments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetDepartment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GetDepartment.Departments departments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDepartments()
    {
        return $this->departments;
    }

    /**
     * Generated from protobuf field <code>repeated .GetDepartment.Departments departments = 1;</code>
     * @param \grpc\GetDepartment\Departments[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDepartments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\GetDepartment\Departments::class);
        $this->departments = $arr;

        return $this;
    }

}

