<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/GetDepartment.proto

namespace grpc\GetDepartment;

use Spiral\RoadRunner\GRPC;

interface GetDepartmentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "GetDepartment.GetDepartmentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetDepartmentRequest $in
    * @return GetDepartmentResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetDepartment(GRPC\ContextInterface $ctx, GetDepartmentRequest $in): GetDepartmentResponse;
}
