<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/SuggestedMember.proto

namespace grpc\SuggestedMember;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SuggestedMember.member</code>
 */
class member extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string department = 3;</code>
     */
    protected $department = '';
    /**
     * Generated from protobuf field <code>string is_on_team = 4;</code>
     */
    protected $is_on_team = '';
    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     */
    protected $profile_image_url = '';
    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     */
    protected $profile_image_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $department
     *     @type string $is_on_team
     *     @type string $profile_image_url
     *     @type string $profile_image_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\SuggestedMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string department = 3;</code>
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * Generated from protobuf field <code>string department = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->department = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string is_on_team = 4;</code>
     * @return string
     */
    public function getIsOnTeam()
    {
        return $this->is_on_team;
    }

    /**
     * Generated from protobuf field <code>string is_on_team = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIsOnTeam($var)
    {
        GPBUtil::checkString($var, True);
        $this->is_on_team = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     * @return string
     */
    public function getProfileImageUrl()
    {
        return $this->profile_image_url;
    }

    /**
     * Generated from protobuf field <code>string profile_image_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     * @return string
     */
    public function getProfileImageName()
    {
        return $this->profile_image_name;
    }

    /**
     * Generated from protobuf field <code>string profile_image_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_name = $var;

        return $this;
    }

}

