<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: ums/SuggestedMember.proto

namespace grpc\SuggestedMember;

use Spiral\RoadRunner\GRPC;

interface SuggestedMemberServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "SuggestedMember.SuggestedMemberService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SuggestedMemberRequest $in
    * @return SuggestedMemberResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SuggestedMember(GRPC\ContextInterface $ctx, SuggestedMemberRequest $in): SuggestedMemberResponse;
}
