<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/SuggestedMember.proto

namespace grpc\SuggestedMember;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SuggestedMember.SuggestedMemberResponse</code>
 */
class SuggestedMemberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .SuggestedMember.member team_lists = 1;</code>
     */
    private $team_lists;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \grpc\SuggestedMember\member[]|\Google\Protobuf\Internal\RepeatedField $team_lists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\SuggestedMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .SuggestedMember.member team_lists = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTeamLists()
    {
        return $this->team_lists;
    }

    /**
     * Generated from protobuf field <code>repeated .SuggestedMember.member team_lists = 1;</code>
     * @param \grpc\SuggestedMember\member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTeamLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \grpc\SuggestedMember\member::class);
        $this->team_lists = $arr;

        return $this;
    }

}

